### ISSUE TITLE
Consider forcing use of session feature flag to enable this API

### ISSUE THREAD

**Issue by willcassella** [immersive-web/lighting-estimation#17]
Lighting estimation has non-trivial privacy and performance concerns, and many apps may not need to use it. Depending on the underlying implementation, there may be a non-trivial startup and per-frame cost for having this API available even if no calls are made. Given that WebXR already has a system for [optional/required session features](https://immersive-web.github.io/webxr/#dictdef-xrsessioninit), it may be beneficial for performance, battery life, and privacy, to introduce a new feature flag to allow apps to signal their intent to use this API.

**Comment by kearwood** [comment]
I agree with this -- I'll add a PR to this effect.

**Comment by kearwood** [comment]
I would like to propose two feature policy flags:

`xr-global-light-estimation` enables `XRLightProbe`, providing values that highly integrated spatially and temporally.
`xr-global-reflection` enables `XRReflectionProbe`, exposing higher frequency information with a greater fingerprinting potential.

For end users (not engine writers), they would see higher-level text...
`xr-global-reflection` = Objects can show detailed, mirror-like, reflections of real world objects.
`xr-global-light-estimation` = Objects will react to the direction and intensity of light.

Some UA's may provide a cube map that was pre-created by the end user in response to `xr-global-reflection`, which may differ from the environment at runtime.  In particular, the user may choose to manually capture a reflection cube map at an earlier time when sensitive information or people are not present in the environment.

**Comment by kearwood** [comment]
All forms of lighting estimation should also require the `xr-spatial-tracking` feature.  This would effectively prevent lighting estimation from being accessed from inline sessions without an indication of user consent.

**Comment by kearwood** [comment]
Landed PR, closing.  Please open a new issue with any feedback.
