### ISSUE TITLE
Use light probes with PRT SH functions to express ambient lighting

### ISSUE THREAD

**Issue by kearwood** [immersive-web/lighting-estimation#2]
I would like to suggest that the lighting estimation be represented as light probes enumerated on an XRFrame.
A modern method of expressing ambient lighting is through Pre-computed Radiance Transform (PRT), encoded as a Spherical Harmonic (SH) function. For more detail: https://patapom.com/blog/SHPortal/
Possible webidl to express such a light probe:
```
[SecureContext, Exposed=Window] interface XRLightProbe {
  Float32Array SHCoefficients;
  attribute XRRigidTransform offset;
  XRSpace space;
};
```
If coefficients contains only a single value, it is to be interpreted as an ambient intensity ambiguous of color or directionality.
If coefficients contains at least 3 values, they are triplets of color component values in r,g,b order. Each triplet forms a coefficient of a spherical harmonic (SH) function. The SH function is interpreted as a Pre-computed Radiance Transform (PRT).
The first coefficient (one r,g,b triplet), forms order 0 of the SH function. These first three values can be interpreted as a constant ambient term ambiguous of directionality.
Additional triplets define the coefficients for higher orders, introducing greater frequency and directionality that may be optionally used by more advanced rendering engines.
coefficients must contain the precise number of values required to contain complete orders. Where "n" is the order, (n+1)^2 coefficients are required.

> eg:
> Order 0: (0+1)^2 = 1 coefficient / 3 values
> Order 1: (1+1)^2 = 4 coefficients / 12 values
> Order 2: (2+1)^2 = 9 coefficients / 27 values
> Order 3: (3+1)^2 = 16 coefficients / 48 values

The color component values of 0.0 to 1.0 are mapped to SRGB color space. Values above 1.0 are allowed in order to express high dynamic range lighting and irradiance values beyond the SRGB gamut.
Rendering engines can choose to either select the nearest light probe for an entire model or to interpolate the lighting components resulting from multiple light probes.
​

**Comment by kearwood** [comment]
If there is no objection from others, I would be glad to pull this into an explainer with proposed webidl to perform enumeration of these light probes.

I believe we can implement this is such a way that simple things are easy (eg, just intensity or rgb ambient values), while allowing the same structure to represent more complete representations of the environment without redundancy.

**Comment by kearwood** [comment]
I expect to see symmetry between hit testing requests and the light probes.  It should be possible to "subscribe" to a light probe once, then see it enumerated by XRFrame for use during RAF.

**Comment by kearwood** [comment]
This would also be the first instance of defining colors in WebXR.  It may be worth discussing how to represent colors outside of the SRGB gamut.  Even when rendering to SRGB output, irradiance values are used in intermediate calculations and should not be so constrained.

**Comment by rcabanier** [comment]
Is WebXR limited to sRGB today? I was under the impression that it could target anything that WebGL supports (which includes HDR and linearRGB)

**Comment by blairmacintyre** [comment]
It seems like a good idea.  I admit to being relatively naive about SH, so I don't have strong feelings for or against the representation (sssh, don't tell my graphics colleagues I said that).  My intuition is that it's a good representation for this, but that's not a strong endorsement. ;)

I like the idea of multiple light probes with multiple values, independent of the SH representation (accepting that the SH will be a good representation for each).

My only question would be if this is both adequate (for reasonable future implementations) and maps to near term implementations.  As you say, the single coefficient is just ambient, which does map to the current ARKit illumination.  Beyond that, or for other platforms ... thoughts?

**Comment by rcabanier** [comment]
Wouldn't it be better if this is done by the OS instead of the JavaScript author?

**Comment by kearwood** [comment]
> 
> 
> Wouldn't it be better if this is done by the OS instead of the JavaScript author?

The expectation is that the higher level platform (such as the OS on mobile devices) provides the data for light-estimation.  The proposal here is just on how to expose this data in a format consistent across all devices to Javascript authors.

For WebGL based rendering, it would need to be  exposed directly to Javascript; however, it could be done more implicitly by not-yet-spec'ed declarative models.

**Comment by kearwood** [comment]
Regarding colors..  I suspect that it may be more effective to represent the r,g,b components in linear space rather than gamma.  Either way, a code sample will be added to the explainer demonstrating how to turn a surface normal into a diffuse color in the SRGB(gamma) space.

**Comment by kearwood** [comment]
> 
> 
> Regarding colors.. I suspect that it may be more effective to represent the r,g,b components in linear space rather than gamma. Either way, a code sample will be added to the explainer demonstrating how to turn a surface normal into a diffuse color in the SRGB(gamma) space.

Another option is to use a physically based measure of irradiance, such as nits (cd/m^2).

**Comment by kearwood** [comment]
In the case of Apple's ARKit 2, spherical harmonic coefficients are returned directly:

https://developer.apple.com/documentation/arkit/ardirectionallightestimate/2928222-sphericalharmonicscoefficients

**Comment by kearwood** [comment]
In addition to the SH ambient, ARKit 2 also predicts the primary light direction and intensity, enabling rendering of self-shadowing and specular. If there is interest in providing direct lighting estimation, the XRLightProbe could provide a natural place for additive extension.

**Comment by kearwood** [comment]
ARKit 2 provides 2nd level order, with 9 coefficients / 27 values

**Comment by kearwood** [comment]
Android's ARCore 1.6 has r,g,b and intensity components.  They are meant to scale final rendered colors in SRGB with a gamma of 2.2.

**Comment by kearwood** [comment]
The various platform API's follow a trend of creating a global light probe then querying its state on a per-frame basis.  It is also possible to have an "unknown" state for the light probe if the estimation could not be made.

It seems that we could start with a simple "global" light probe representing the lighting estimate for the space near the observer and later additively enable arbitrary light probe placement within an XRSpace.

**Comment by kearwood** [comment]
The AR-in-VR use case would likely be the first driver for having multiple light probes in the scene, as they would be computed directly from known geometry.  It is possible that real-world AR could rapidly reach the same capability; however.

**Comment by kearwood** [comment]
Just wish to bump, and say that an explainer is coming soon.

Also, Three.js has recently merged support for Light Probes with Spherical Harmonics, compatible with this ambient lighting proposal:

https://github.com/mrdoob/three.js/pull/16223

**Comment by blairmacintyre** [comment]
FWIW, ARKit now supports generating cube-map reflection map probes at multiple points in the scene;  I assume these could be leveraged for this purpose?

**Comment by kearwood** [comment]
> FWIW, ARKit now supports generating cube-map reflection map probes at multiple points in the scene; I assume these could be leveraged for this purpose?

Some searching turned up a nice little JS function to convert such cube maps to the 9 SH coefficients:

https://github.com/nicknikolov/cubemap-sh

Note that this would reproduce only low frequency detail (eg, ambient light) as opposed to crisp reflections.  Be sure to use or covert to linear space from gamma before encoding.  Ideally, this would be done in an HDR color space as the SH light probe would represent light received by the point, which would be attenuated down to a level typically rendered in display space, such as SRGB or rec. 2020..

In addition to exposing a "Light Probe" analogue measured from the real world environment (or nested VR environment), perhaps it would also be interesting to expose a "Reflection Probe" analogue as an HDR cube map.

Due to their cheap nature, it is feasible to have many SH based light probes, but having a relatively nearby approximated Reflection Probe to blend in could help round out the rendering.

**Comment by mrdoob** [comment]
Just want to say that three.js now support SH too. And we also have a `fromCubeTexture()` method.
https://threejs.org/examples/webgl_lightprobe.html

**Comment by blairmacintyre** [comment]
Cool.  Ironically, for my use (prototyping WebXR in our iOS WebXR Viewer app), I need to convert the cubetexture to SH in native code ... I assume there's a library for that somewhere.  (the constraint I have is that the bridge from native->JS is expensive, so I don't actually want to send those maps in)

**Comment by kearwood** [comment]
PSA - I expect to move forward on this a bit more next week.  I'll try to incorporate the ideas from the excellent feedback here.

**Comment by kearwood** [comment]
All of the feedback on the PR has been very useful -- I think most of it should be incorporated into the explainer.  If there are no objections, I would like to land this PR and break out the individual comments into separate issues so we can work on them individually.  Does this sound okay?

**Comment by kearwood** [comment]
Now that the initial PR has merged with an explainer, I'll close this issue.  Please file issues if I haven't captured any follow-up work from this thread.
